### ISSUE TITLE
Compatibility with Galileo

### ISSUE THREAD

**Issue by spudwebb** [arduino-libraries/MIDIUSB#30]
Hi,

Is there any way to make this library compatible with a Galileo board?
It seems that the Galileo core files do not have the needed PluggableUSB library. Is there any workaround?

If not, what would be the best way to read MIDI messages sent from a MIDI USB instrument, on a Galileo board.

thanks

**Comment by facchinm** [comment]
Hi @spudwebb ,
since Galileo runs Linux, you can use all the Linux tools to ease your task. This (https://wiki.archlinux.org/index.php/USB_MIDI_keyboards) is a very exhaustive guide on how to read messages from a MIDI USB instrument on Linux. 
This library performs the opposite, so your board becomes a MIDI USB instrument; even if it worked on Galileo it's not exactly what you are trying to achieve :wink: 
Hope it helps!
