### ISSUE TITLE
error on MIDIUSB

### ISSUE THREAD

**Issue by Walfried** [arduino-libraries/MIDIUSB#69]
When I try to compile my scetch I get the  error "#error MIDIUSB can only be used with an USB MCU"
My board is  an Arduino Mega2560 R3 and it should be working (it's on the list)
https://www.arduino.cc/reference/en/libraries/midiusb/
Any suggestions?
Thanks for the help.

**Comment by per1234** [comment]
Hi @Walfried. Thanks for taking the time to submit an issue.

That "#error MIDIUSB can only be used with an USB MCU" is correct. This library can only be used with the Arduino boards that have native USB capabilities such as the [Leonardo](https://store.arduino.cc/arduino-leonardo-with-headers), [Micro](https://store.arduino.cc/arduino-micro), [MKR](https://store.arduino.cc/catalogsearch/result/?tab=store&q=mkr), and [Nano 33 IoT](https://store.arduino.cc/arduino-nano-33-iot) boards.

The information on the reference page is automatically generated. It lists the official Arduino boards of the AVR architecture, but in this case some of those boards are not supported by this library because they don't have native USB capabilities.

I have passed your report on to the developers of the library reference.
